### ISSUE TITLE
[Snacktime] Console error KeyError: 'Snackburr'

### ISSUE THREAD

**Issue by Brandjuh** [aikaterna/aikaterna-cogs#116]
```
May 24 07:33:40 ThePoliceBot python[550]: Ignoring exception in on_message
May 24 07:33:40 ThePoliceBot python[550]: Traceback (most recent call last):
May 24 07:33:40 ThePoliceBot python[550]:   File "/root/redenv/lib/python3.8/site-packages/discord/client.py", line 312, in _run_event
May 24 07:33:40 ThePoliceBot python[550]:     await coro(*args, **kwargs)
May 24 07:33:40 ThePoliceBot python[550]:   File "/root/.local/share/Red-DiscordBot/data/cuffbotv3/cogs/CogManager/cogs/snacktime/snacktime.py", line 333, in on_message
May 24 07:33:40 ThePoliceBot python[550]:     await self.startSnack(message)
May 24 07:33:40 ThePoliceBot python[550]:   File "/root/.local/share/Red-DiscordBot/data/cuffbotv3/cogs/CogManager/cogs/snacktime/snacktime.py", line 256, in startSnack
May 24 07:33:40 ThePoliceBot python[550]:     self.channel_persona[scid] = await self.persona_choice(message)
May 24 07:33:40 ThePoliceBot python[550]:   File "/root/.local/share/Red-DiscordBot/data/cuffbotv3/cogs/CogManager/cogs/snacktime/snacktime.py", line 57, in persona_choice
May 24 07:33:40 ThePoliceBot python[550]:     del personas["Snackburr"]
May 24 07:33:40 ThePoliceBot python[550]: KeyError: 'Snackburr'
```

**Comment by aikaterna** [comment]
Have you edited the cog?

**Comment by Brandjuh** [comment]
Nop, didn't change anything. Just came in in the console, not as traceback error.

**Comment by aikaterna** [comment]
https://github.com/aikaterna/aikaterna-cogs/commit/c40fd6b32f899d38c146e611d7cc4b1e3a98a079
