### ISSUE TITLE
[CAH] if user has bot blocked/dms denied it can cause mutliple errors

### ISSUE THREAD

**Issue by kennnyshiwa** [aikaterna/aikaterna-cogs#120]
```
Exception in command 'chat'
Traceback (most recent call last):
  File "/home/kenny/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/kenny/bb/Red-DiscordBot/cogs/CogManager/cogs/cah/cah.py", line 893, in chat
    await member["User"].send(msg)
  File "/home/kenny/redenv/lib/python3.8/site-packages/discord/abc.py", line 870, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
  File "/home/kenny/redenv/lib/python3.8/site-packages/discord/http.py", line 240, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50007): Cannot send messages to this user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kenny/redenv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "/home/kenny/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 824, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/kenny/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: Forbidden: 403 Forbidden (error code: 50007): Cannot send messages to this user
```

this is just one of the errors, but say the same thing for lay, chat and for even joincah as well

**Comment by aikaterna** [comment]
379a37a
