### ISSUE TITLE
[Youtube] list index out of range

### ISSUE THREAD

**Issue by ax5nonymous** [aikaterna/aikaterna-cogs#129]
I keep getting the following error when trying to use the youtube command. It happens regardless of the search query used. I am running version 3.3.9 of RedBot.

```
[2020-06-29 20:08:28] [ERROR] red: Exception in command 'youtube'
Traceback (most recent call last):
  File "c:\users\redenv\lib\site-packages\discord\ext\commands\core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\Red\cogs\CogManager\cogs\youtube\youtube.py", line 38, in youtube
    await ctx.send(result[0])
IndexError: list index out of range

```

**Comment by aikaterna** [comment]
Update your cog. This is resolved by having the current version.
