### ISSUE TITLE
[NoFlippedTables] Bot errors in console if it doesn't have perms to send message to destination channel.

### ISSUE THREAD

**Issue by owocado** [aikaterna/aikaterna-cogs#147]
```py
Ignoring exception in on_message

Traceback (most recent call last):
  File "/home/ubuntu/merlin/lib/python3.8/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/merlin/cogs/CogManager/cogs/noflippedtables/noflippedtables.py", line 135, in on_message
    await channel.send(tables)
  File "/home/ubuntu/merlin/lib/python3.8/site-packages/discord/abc.py", line 890, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
  File "/home/ubuntu/merlin/lib/python3.8/site-packages/discord/http.py", line 241, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
```

It would be nice if it can be handled gracefully. :D

**Comment by aikaterna** [comment]
https://github.com/aikaterna/aikaterna-cogs/commit/2a27d9012eb728e5a450ed5199dd92e299430290
