### ISSUE TITLE
Cannot find a RSS feed (Specific link?)

### ISSUE THREAD

**Issue by madebylydia** [aikaterna/aikaterna-cogs#199]
I tried to search for a feed on the following URL: https://predeactor.net

The command had an error and the traceback is the following:

```py
Exception in command 'rss find'
Traceback (most recent call last):
  File "/home/ubuntu/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/ubuntu/bots/Miku/cogs/CogManager/cogs/rss/rss.py", line 665, in _rss_find
    soup = BeautifulSoup(await response.text(), "html.parser")
  File "/home/ubuntu/redenv/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1014, in text
    return self._body.decode(encoding, errors=errors)  # type: ignore
  File "/usr/lib/python3.8/encodings/cp1254.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 354: character maps to <undefined>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/redenv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/redenv/lib/python3.8/site-packages/redbot/core/commands/commands.py", line 825, in invoke
    await super().invoke(ctx)
  File "/home/ubuntu/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1329, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/home/ubuntu/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 859, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/ubuntu/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 354: character maps to <undefined> 
```

**Comment by aikaterna** [comment]
d408adddd82cd716a561ef273ae9239eaa3b94bf
