### ISSUE TITLE
[Hunting] Got an error while doing [p]hunting

### ISSUE THREAD

**Issue by deXxterlab97** [aikaterna/aikaterna-cogs#272]
Version: 3.1.7

When doing just `[p]hunting` it throws an error:

```Error in command 'hunting'. Check your console or logs for details.`

Doing `[p]traceback true` shows this

```
Exception in command 'hunting'
Traceback (most recent call last):
  File "/home/pi/redenv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/pi/red01/cogs/CogManager/cogs/hunting/hunting.py", line 86, in hunting
    reward = await self.config.reward_range()
  File "/home/pi/redenv/lib/python3.9/site-packages/redbot/core/config.py", line 762, in __getattr__
    return getattr(global_group, item)
  File "/home/pi/redenv/lib/python3.9/site-packages/redbot/core/config.py", line 354, in __getattr__
    raise AttributeError("'{}' is not a valid registered Group or value.".format(item))
AttributeError: 'reward_range' is not a valid registered Group or value.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/redenv/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/pi/redenv/lib/python3.9/site-packages/redbot/core/commands/commands.py", line 821, in invoke
    await super().invoke(ctx)
  File "/home/pi/redenv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 1342, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/pi/redenv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'reward_range' is not a valid registered Group or value.
```

Everything else seems to work fine, including the cog functionality and the help menu when doing `[p]help hunting`

**Comment by aikaterna** [comment]
Fixed in https://github.com/aikaterna/aikaterna-cogs/commit/d1efba9abd04cceac0f33495610b13758e4561f4
