### ISSUE TITLE
[IcyParser] Error when command is run with no URL and no active player

### ISSUE THREAD

**Issue by leetfin** [aikaterna/aikaterna-cogs#273]
Exactly as the title says.
Expected behavior: A nice message saying no player. not a traceback.

```py
Traceback (most recent call last):
  File "/home/ubuntu/redenv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/ubuntu/bots/Cobalt/cogs/CogManager/cogs/icyparser/icyparser.py", line 148, in icyparser
    player = lavalink.get_player(ctx.guild.id)
  File "/home/ubuntu/redenv/lib/python3.9/site-packages/lavalink/lavalink.py", line 124, in get_player
    node_ = node.get_node(guild_id)
  File "/home/ubuntu/redenv/lib/python3.9/site-packages/lavalink/node.py", line 602, in get_node
    raise IndexError("No nodes found.")
IndexError: No nodes found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/redenv/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/redenv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/ubuntu/redenv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: IndexError: No nodes found.

```

**Comment by aikaterna** [comment]
Should be fixed because I rewrote the whole thing again. 
![kappa](https://user-images.githubusercontent.com/20862007/163898999-a226feaa-d000-488f-b048-5d001db38695.png)

Try https://github.com/aikaterna/aikaterna-cogs/commit/4cbce0e538d6d1986266b9c0debcd583863fc958 and see what you think.

**Comment by aikaterna** [comment]
Or just update in general because I had to push another fix for current Red vs. Red dev. :aha:
