### ISSUE TITLE
[timezone] Fuzzywuzzy no longer a Red 3.5 dependency, breaking cog

### ISSUE THREAD

**Issue by synrg** [aikaterna/aikaterna-cogs#311]
In https://github.com/Cog-Creators/Red-DiscordBot/pull/5611 fuzzywuzzy was removed from Red. This means that in a fresh python 3.11 venv with red 3.5, when you try to load timezone, it breaks:

```py
Exception during loading of package
Traceback (most recent call last):
  File "/home/redbot/venvs/red-3.5/lib/python3.11/site-packages/redbot/core/core_commands.py", line 188, in _load
    await bot.load_extension(spec)
  File "/home/redbot/venvs/red-3.5/lib/python3.11/site-packages/redbot/core/bot.py", line 1680, in load_extension
    lib = spec.loader.load_module()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 605, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1120, in load_module
  File "<frozen importlib._bootstrap_external>", line 945, in load_module
  File "<frozen importlib._bootstrap>", line 290, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 721, in _load
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/redbot/.local/share/Dumbo/cogs/CogManager/cogs/timezone/__init__.py", line 1, in <module>
    from .timezone import Timezone
  File "/home/redbot/.local/share/Dumbo/cogs/CogManager/cogs/timezone/timezone.py", line 4, in <module>
    from fuzzywuzzy import fuzz, process
ModuleNotFoundError: No module named 'fuzzywuzzy'
```

Workaround: install fuzzywuzzy in your python env.

This could be fixed by adding fuzzywuzzy to the info.json so it is installed with the cog, or you could go with what Red uses now which is rapidfuzz.

**Comment by aikaterna** [comment]
Hi, thank you for leaving an issue. https://github.com/aikaterna/aikaterna-cogs/commit/9f6e4b711460b7f7e8c66629d0225f86b266d4f2 will resolve this by adding fuzzywuzzy as a dep. When working with rapidfuzz inside Red while helping with updating to 3.5, I was disappointed in my results vs what I was getting as output for similar fuzzywuzzy levels of fuzz, so I will leave this as fuzzywuzzy for now. I am slated to do some fine-tuning work on the rapidfuzz use inside a specific part of Red later on, so when I get to that work and I understand the fuzzy tuning requirements of rapidfuzz a little better, I may choose to change to that for timezone.
