### ISSUE TITLE
ImportError: cannot import name '_imaging' from 'PIL' in leveler (Ubuntu,Bionic) 

### ISSUE THREAD

**Issue by Edgar06ka** [aikaterna/aikaterna-cogs#48]
[2019-07-03 21:28:19] [ERROR] red: Package loading failed
Traceback (most recent call last):
File "/home/edgar06ka/bot/lib/python3.7/site-packages/redbot/core/core_commands.py", line 104, in _load
await bot.load_extension(spec)
File "/home/edgar06ka/bot/lib/python3.7/site-packages/redbot/core/bot.py", line 252, in load_extension
lib = spec.loader.load_module()
File "", line 405, in _check_name_wrapper
File "", line 905, in load_module
File "", line 730, in load_module
File "", line 265, in _load_module_shim
File "", line 696, in _load
File "", line 677, in _load_unlocked
File "", line 726, in exec_module
File "", line 219, in _call_with_frames_removed
File "/home/edgar06ka/mybot/cogs/CogManager/cogs/leveler/init.py", line 1, in 
from .leveler import Leveler
File "/home/edgar06ka/mybot/cogs/CogManager/cogs/leveler/leveler.py", line 4, in 
from PIL import Image, ImageDraw, ImageFont, ImageColor, ImageOps, ImageFilter
File "/home/edgar06ka/mybot/cogs/Downloader/lib/PIL/Image.py", line 60, in 
from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/home/edgar06ka/mybot/cogs/Downloader/lib/PIL/init.py)

**Comment by aikaterna** [comment]
You need to pip3 install pillow on that machine. You can run `[p]pipinstall pillow` via your bot if you want instead. If you installed this repo through downloader, it should install all of the requirements for you when you install the cog.
