### ISSUE TITLE
[Retrosign] Page scraping needs to be changed

### ISSUE THREAD

**Issue by aikaterna** [aikaterna/aikaterna-cogs#57]
```
Exception in command 'retrosign'
Traceback (most recent call last):
  File "c:\venv\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "c:\bot\cogs\CogManager\cogs\retrosign\retrosign.py", line 72, in retrosign
    download_url = soup.find("div", class_="downloads-container").ul.li.a["href"]
AttributeError: 'NoneType' object has no attribute 'ul'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\venv\lib\site-packages\discord\ext\commands\bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "c:\venv\lib\site-packages\discord\ext\commands\core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "c:\venv\lib\site-packages\discord\ext\commands\core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'ul'
```

**Comment by alphasixtyfive** [comment]
Using PhotoFunia is against their TOS and any code associated with it should be removed.

**Comment by aikaterna** [comment]
Lucky you, I was intending to depreciate the cog at some point, however, you should prove your claims. Next time open an issue instead of commenting on something that's been closed for over a year.
