### ISSUE TITLE
[CAH] Starting a New Game Doesn't Draw a Black Card

### ISSUE THREAD

**Issue by LGACode** [aikaterna/aikaterna-cogs#89]
Cannot start a game of CAH because the black card is never drawn which causes the following error when using the ```lay``` command:

```python
Exception in command 'lay'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/app/cogs/CogManager/cogs/cah/cah.py", line 968, in lay
    numberCards = userGame["BlackCard"]["Pick"]
TypeError: 'NoneType' object is not subscriptable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: 'NoneType' object is not subscriptable

```

![image](https://user-images.githubusercontent.com/6125912/71545523-22b72200-2949-11ea-978b-7a38d84b0024.png)

**Comment by LGACode** [comment]
See screenshots for troubleshooting up to this point. Bot was reloaded, cog was reloaded as well as reinstalled. No change in behavior.

![image](https://user-images.githubusercontent.com/6125912/71545509-01563600-2949-11ea-9308-28d056583f53.png)

![image](https://user-images.githubusercontent.com/6125912/71545514-0d41f800-2949-11ea-9777-f5b16641c9f2.png)

**Comment by aikaterna** [comment]
I can't repro this.

**Comment by aikaterna** [comment]
I have not been able to reproduce this nor has anyone else reported this yet. If there are other reports in the future I will look back into this.
