### ISSUE TITLE
[Dictionary] Underlying service is down

### ISSUE THREAD

**Issue by aikaterna** [aikaterna/aikaterna-cogs#91]
```
Traceback (most recent call last):
  File "/.../lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/.local/share/Red-DiscordBot/cogs/CogManager/cogs/dictionary/dictionary.py", line 54, in define
    result = await self._definition(ctx, search_term)
  File "/root/.local/share/Red-DiscordBot/cogs/CogManager/cogs/dictionary/dictionary.py", line 78, in _definition
    types = html.findAll("h3")
AttributeError: 'NoneType' object has no attribute 'findAll'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/.../lib/python3.7/site-packages/discord/ext/commands/bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "/.../lib/python3.7/site-packages/discord/ext/commands/core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/.../lib/python3.7/site-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'findAll'
```

**Comment by aikaterna** [comment]
Seems to be back up.
